config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true

  scope :active, -> {where(completed: false)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos • Vue.js</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :task_content %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed, id: :task_completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="todos" id="todos-app">
  <header>
    <h1>todos</h1>
  </header>

  <section class="main">
    <input v-model="task.content" @keyup.enter="addTask($event)" autofocus="true" class="new-task" placeholder="What needs to be done?">
    <input type="checkbox" class="toggle-all">

    <ul class="todo-list">
      <task-item v-for="(task, index) in filteredTasks" :task="task" :key="task.id"
        @delete="deleteTask($event)"
        @update="updateTask($event)">
      </task-item>
    </ul>
  </section>

  <footer class="footer">
    <span class="task-count">
      <strong>{{ remaining }}</strong> items left
    </span>
    <ul class="filters">
      <li><a href="#all" @click="all" :class="{ selected: currentFilter == 'all' }">All</a></li>
      <li><a href="#active" @click="activeTasks" :class="{ selected: currentFilter == 'active' }">Active</a></li>
      <li><a href="#completed" @click="completedTasks" :class="{ selected: currentFilter == 'completed' }">Completed</a></li>
    </ul>
  </footer>
</div>

<template id="task-item">
  <div>
    <li class="task" :class="{ completed: task.completed }">
      <div class="view">
        <input class="toggle" type="checkbox" v-model="task.completed" @change="updateTask">
        <label><input type="text" v-model="task.content" @change="updateTask"></label>
        <button class="destroy" @click="removeTask"></button>
      </div>
    </li>
  </div>
</template>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>